import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import SessionProvider from '@/components/SessionProvider';
import getServerSession from '@/lib/getServerSession';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { App } from 'antd';

import 'normalize.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang='en'>
      <body className={inter.className}>
        <SessionProvider session={session}>
          <AntdRegistry>
            <App>
              <main>{children}</main>
            </App>
          </AntdRegistry>
        </SessionProvider>
      </body>
    </html>
  );
}
